# Ikaros-project.org
#
# Find the ArtoolkitPlus includes and library
#
# This module defines
# ARTOOLKITPLUS_INCLUDE_DIR
# ARTOOLKITPLUS_LIBRARIES
# ARTOOLKITPLUS_FOUND


FIND_PATH(ARTOOLKITPLUS_INCLUDE_DIR1 ARToolKitPlus.h
  /usr/local/include/ARToolKitPlus
)

FIND_LIBRARY(ARTOOLKITPLUS_LIBRARY1 ARToolKitPlus
  /usr/local/lib/ARToolKitPlus
)

IF (ARTOOLKITPLUS_INCLUDE_DIR1)
	SET(ARTOOLKITPLUS_INCLUDE_DIR
	${ARTOOLKITPLUS_INCLUDE_DIR1}
	)
ENDIF (ARTOOLKITPLUS_INCLUDE_DIR1)

IF (ARTOOLKITPLUS_LIBRARY1)
	SET(ARTOOLKITPLUS_LIBRARIES
	${ARTOOLKITPLUS_LIBRARY1}
	)
    message(STATUS "Found ArToolKitPlus:")
	message(STATUS " - Includes: ${ARTOOLKITPLUS_INCLUDE_DIR}")
	message(STATUS " - Libraries: ${ARTOOLKITPLUS_LIBRARIES}")
	SET(ARTOOLKITPLUS_FOUND "YES" )
ENDIF (ARTOOLKITPLUS_LIBRARY1)

